duka/duka/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('storeApp.urls',  namespace='storeApp')),
]

duka/storeApp/urls.py
from django.urls import path, include
from . import views 

app_name = 'storeApp'

urlpatterns = [
    path('', views.loginPage, name="loginPage"),
    path('homepage', views.homepage, name="homepage"),
    path('logout-user', views.logoutPage, name="logoutPage"),
    path('storePage', views.storePage, name="storePage"),
    path('my-shops', views.shopPage, name="shopPage"),
    path('my-suppliers', views.suppliersPage, name="suppliersPage"),
    path('my-employees', views.employeePage, name="employeePage"),
    path('my-sales', views.salesPage, name="salesPage"),
    path('my-products', views.productPage, name="productPage"),
    path('my-orders', views.ordersPage, name="ordersPage"),
    path('my-emergence', views.emergencePage, name="emergencePage"),
    path('users-authorization', views.authorizationPage, name="authorizationPage"),
    path('change-order-status/<str:id>/', views.changeOrderStatus, name="changeOrderStatus"),
    path('update-order/<str:id>/', views.updateOrder, name="updateOrder"),
    path('delete-order/<str:id>/', views.deleteOrder, name="deleteOrder"),
    path('update-emergence/<str:id>/', views.updateEmergence, name="updateEmergence"),
    path('delete-emergence/<str:id>/', views.deleteEmergence, name="deleteEmergence"),
    path('update-user-auth/<str:id>/', views.updateUserAuthorizations, name="updateUserAuthorizations"),
    path('delete-user-auth/<str:id>/', views.deleteUserAuthorizations, name="deleteUserAuthorizations"),
    path('delete/<str:id>/', views.deleteUser, name="deleteUser"),
    path('delete-shop/<str:id>/', views.deleteShop, name="deleteShop"),
    path('delete-product/<str:id>/', views.deleteProduct, name="deleteProduct"),
    path('delete-supplier/<str:id>/', views.deleteSupplier, name="deleteSupplier"),
    path('delete-product-sold/<str:id>/', views.deleteProductSold, name="deleteProductSold"),
    path('delete-product-in-store/<str:id>/', views.deleteProductInStore, name="deleteProductInStore"),
    path('activate-user/<str:id>/', views.activateUserAuthorizations, name="activateUserAuthorizations"),
    path('deactivate-user/<str:id>/', views.deactivateUserAuthorizations, name="deactivateUserAuthorizations"),
    path('pdf/', views.myView, name="myView"),
    path('company-Stock', views.companyStockPage, name="companyStockPage"),
]

duka/templates/store/barGraph2.html
<div class="bar_graph">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div style="width:100%;">
          <canvas id="chart2"></canvas>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
// var chart = new Chart(ctx).Line(data, options);
var canvas = document.getElementById('chart2');
new Chart(canvas, {
  type: 'bar',
  data: {
    labels: ['sembe', 'unga wa ngano', 'biscuti nice g10', 'azam juice ml-100', 'maji ya uhai lita 10', 'sembe kg50', 'unga wa ngano kg 50', 'biscuti nice g50', 'azam juice ml-300', 'maji ya uhai lita 20'],
    datasets: [{
      label: 'product in',
      yAxisID: 'A',
      data: [10, 96, 84, 76, 69,200, 56, 84, 86, 70]
    }, {
      label: 'product out',
      yAxisID: 'B',
      data: [100, 50, 20, 0, 40, 200, 50, 10, 20, 40]
    }]
  },
  options: {
    scaleUse2Y: true,
    scales: {
      yAxes: [{
        id: 'A',
        type: 'linear',
        position: 'left',
       
      }, 
      {
        id: 'B',
        type: 'linear',
        position: 'right',
        // ticks: {
        //   max: 1,
        //   min: 0
        // }
      }],
      xAxes: [{
                ticks: {
                    autoSkip: false,
                    maxRotation: 80,
                    minRotation: 20
                }
            }]

      
    }
  }
});
</script>

duka/templates/store/companyStockDataTable.html
<div class="table_section mb-5">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xl-12 col-lg-12 mb-4">
          <div class="card">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
              <h6 class="m-0 font-weight-bold text-primary">Assets</h6>
              <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#companyAssetstModal"
              id="#companyAssetstModal"><i class="fas fa-plus p-1"></i>Assets</button>
              </div>
                {% if get_all_company_stock %}
                <div class="table-responsive p-4">
                <table class="table table-md align-items-center table-flush table-hover" id="dataTableHover">
                    <thead class="thead-light">
                        <tr>
                        <th>#</th>
                        <th>Stock Name</th>
                        <th>Stock number</th>
                        <th>Stock color </th>
                        <th>Stock size </th>
                        <th>Date recorded </th>
                        <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for stock in get_all_company_stock %}
                        <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="#">{{stock.stock_name}}</a></td>
                                            
                        <td>{{stock.stock_number}}</td>
                        <td>{{stock.stock_color}}</td>
                        <td>{{stock.stock_size}}</td> 
                        <td>{{stock.updated_at}}</td> 
                        
                        <td>
                            <a data-toggle="modal" data-target="#productDetailViewModal{{stock.id}}" class="btn btn-sm btn-outline-primary text-primary"><i class="fas fas fa-eye"></i></a>
                            <a  data-toggle="modal" data-target="#updateproductModal{{stock.id}}"
                            class="btn btn-sm btn-outline-warning"  ><i class="fas fas fas fa-pen"></i></a>
                            <a  data-toggle="modal" data-target="#deleteProductModal" class="btn btn-sm btn-outline-danger"><i class="fas fas fas far fa-trash-alt"></i></a>
                        </td>
                        </tr>
                        {% include './deleteCompanyStockModal.html' %}
                        
                        {% endfor %}
                    </tbody>
                    </table>
                
                </div>
                {% else %}
                <div class="table-responsive pl-2">
                <div class="empty_content">
                    <p> No Assets or Stock  added yet! </p>
                </div>
                </div>
                {% endif %}
            <div class="card-footer"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% include './companyAssetstModal.html' %}


  <!-- ========================= -->
  

duka/templates/store/companyStockPage.html
{% extends './base.html' %}
{% load static %}
{% block title %} Company stocks {% endblock %}
{% block content %}
{% if get_all_user_authorizations.view_dashboard  and get_all_user_authorizations.manage_product %}


{% include './companyStockStatusBar.html' %}
{% include './companyStockDataTable.html' %}
{% endif %}
{% endblock %}

duka/templates/store/deleteProductSoldModal.html
<div class="modal fade" id="deleteProductSoldModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabelLogout"
aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="deleteProductSoldModal"><code>Attention</code>!</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <p>Are you sure you want to Delete this product sold  information ?</p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-outline-primary" data-dismiss="modal">No</button>
      <a href="{% url 'storeApp:deleteProductSold' product_sold.id %}" class="btn btn-outline-primary">Yes</a>
    </div>
  </div>
</div>
</div>

duka/templates/store/employeeStatusBar.html
<div class="container-fluid" id="container-wrapper">

<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Employees</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="./">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Employees</li>
  </ol>
</div>

<div class="row mb-3">
  <!-- Earnings (Monthly) Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card h-100">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-uppercase mb-1">Total Employees</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{get_number__of_all_employee}}</div>
            <div class="mt-2 mb-0 text-muted text-xs">
              <!-- <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span> -->
              <!-- <span>Since last month</span> -->
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fas fa-users fa-2x text-primary"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Earnings (Annual) Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card h-100">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-uppercase mb-1">Employee with active account</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{get_number__of_all_employee_with_account}}</div>
            <div class="mt-2 mb-0 text-muted text-xs">
              <!-- <span class="text-success mr-2"><i class="fas fa-arrow-up"></i> 12%</span>
              <span>Since last years</span> -->
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fas fa-user-shield fa-2x text-success"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- New User Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card h-100">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-uppercase mb-1">USERS WITH NO ACCOUNT</div>
            <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{get_number__of_all_employee_with_no_account}}</div>
            <div class="mt-2 mb-0 text-muted text-xs">
              <!-- <span class="text-success mr-2"><i class="fas fa-arrow-up"></i> 20.4%</span>
              <span>Since last month</span> -->
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fas fa-users fa-2x text-info"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Pending Requests Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card h-100">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-uppercase mb-1">PENDING EMPLOYEE ACCOUTS</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">0</div>
            <div class="mt-2 mb-0 text-muted text-xs">
              <!-- <span class="text-danger mr-2"><i class="fas fa-arrow-down"></i> 1.10%</span>
              <span>Since yesterday</span> -->
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fas fa-user-lock fa-2x text-danger"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

duka/templates/store/productPage.html
{% extends './base.html' %}
{% load static %}
{% block title %} Products {% endblock %}
{% block content %}
{% if get_all_user_authorizations.view_dashboard  and get_all_user_authorizations.manage_product %}


{% include './productsStatusBar.html' %}
{% include './productDataTables.html' %}
{% endif %}
{% endblock %}

duka/templates/store/salesModal.html
<!-- The Modal -->
<div class="modal  fade w3-animate-zoom" id="salesModal">
  <div class="modal-dialog  modal-dialog-centered">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title"><strong>sell product from store</strong></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <div class="card mb-4">
          <!-- <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Form Basic</h6>
          </div> -->
          <div class="card-body">
            <form method="post" action="">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-12">
                  {% if get_all_products %}
                  <div class="form-group">
                    <label for="select2SinglePlaceholder" class="d-block"> select product</label>
                    <select class="select2-single-placeholder-product form-control" name="product_name" id="select2SinglePlaceholderproduct12" style="width: 100%;padding:10px">
                      <option value="not selected">Select</option>
                      {% for products in get_all_products %}
                      <option value="{{ products.id }}">{{products}}</option>
                      {% endfor %}
                    </select>
                  </div>
                  {% endif %}
                </div>
                <div class="col-md-6">
                 <div class="form-group">
                   <label for="quantity" >Number of products nedeed</label>
                   <input type="number" name="number_of_product_nedeed" class="form-control">
                 </div>
                 </div>
                 <div class="col-md-6">
                  <!-- <div class="form-group">
                    <label for="Supplier" >today  date</label>
                    <input type="date" name="date_product_sold" class="form-control">
                  </div> -->
                 
                   {% if get_all_shops %}
                  <div class="form-group">
                    <label for="select2SinglePlaceholder" class="d-block"> select Shop</label>
                    <select class="select2-single-placeholder-duka form-control" name="shop_name" id="select2SinglePlaceholderduka12" style="width: 100%;padding:10px">
                      <option value="not selected">Select</option>
                      {% for shop in get_all_shops %}
                      <option value="{{shop.id}}">{{shop}}</option>
                      {% endfor %}
                    </select>
                  </div>
                  {% endif %}
                   </div>
              

               <button type="submit" class="btn btn-primary ml-3" name="sell_product" value="sell_product">sell product</button>
            
              </div>
             </form>
          </div>
        </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>

duka/templates/store/salesPage.html
{% extends './base.html' %}
{% load static %}
{% block title %} Sales{% endblock %}
{% block content %}

{% include './salesStatusBar.html' %}
{% include './salesDatatables.html' %}


{% endblock %}

duka/templates/store/shopDetailViewModal.html
<div class="modal  fade w3-animate-zoom" id="shopDetailViewModal{{shops.id}}">
  <div class="modal-dialog  modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h5 class="modal-title"><strong> information about  <code>{{shops.shop_name}}</code> </strong></h5>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <div class="card mb-4">
          <div class="card-body">
            <!-- <h5><span>shop id</span> : <code>{{shops.id}} </code></h5> -->
            <h5><span>shop name</span> : <code>{{shops.shop_name}} </code></h5>
            <h5><span>street located </span> : <code>{{shops.shop_street}} </code></h5>
            <h5> <span>district located</span> : <code>{{shops.shop_district}} </code></h5>
            <h5> <span>region located</span> : <code>{{shops.shop_region}} </code></h5>
            <h5> <span>registered since </span> : <code>{{shops.shop_start_date}} </code></h5>
            <h5> <span>phone number 2</span> : <code>{{shops.shops_phone_number2}} </code></h5>
            <h5> <span>shop supervisor </span> : <code>{{shops.shop_supervisor}} </code></h5>
           
          </div>
        </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>

duka/templates/store/shopPage.html
{% extends './base.html' %}
{% load static %}
{% block title %} shops{% endblock %}
{% block content %}

{% include './shopStatusBar.html' %}
{% include './shopDatatables.html' %}
<!-- The Modal -->
<div class="modal  fade w3-animate-zoom" id="myModal">
  <div class="modal-dialog  modal-dialog-centered">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title"><strong>Add new shop</strong></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <div class="card mb-4">
          <!-- <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Form Basic</h6>
          </div> -->
          <div class="card-body">
            <form action="" method="post">
              {% csrf_token %}
             <div class="row">
               <div class="col-md-6">
                <div class="form-group">
                  <label for="ProductName">Shop name</label>
                  <input type="text" name= "shop_name" class="form-control">
                </div>
                <div class="form-group">
                  <label for="quantity" >Street</label>
                  <input type="text" name="quantity_of_product_received" class="form-control">
                </div>
                <div class="form-group">
                  <div class="custom-file">
                    <label  for="costOfEachProudct">District</label>
                    <input type="text" name="coast_of_each_product" class="form-control">
                  </div>
                </div>
                <div class="form-group">
                  <label for="Supplier" >Region</label>
                  <input type="text" name="Supplier_name" class="form-control">
                </div>
                
               </div>
               <div class="col-md-6">
                <div class="form-group">
                  <label for="Supplier" >Start date</label>
                  <input type="date" name="Supplier_phone_number" class="form-control">
                </div>
                <div class="form-group">
                  <label for="Supplier" >Capital</label>
                  <input type="text" name="date_product_received" class="form-control">
                </div>
                <div class="form-group">
                  <label for="Supplier" >Surpervisor </label>
                  <input type="text" name="shop_received_product" class="form-control">
                </div>
                <div class="form-group">
                  <label for="Supplier" >Surpervisor phone </label>
                  <input type="text" name="shop_received_product" class="form-control">
                </div>
              </div>
              <button type="submit" class="btn btn-primary ml-3">Submit</button>

             </div>
            </form>
          </div>
        </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>



{% endblock %}

duka/templates/store/supplierModal.html
<div class="modal fade" id="supplierModal" tabindex="-1" role="dialog"
aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalCenterTitle">Supplier infomation</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="card mb-4">
        <!-- <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Form Basic</h6>
        </div> -->
        <div class="card-body">
          <form action ="" method="POST" >
            {% csrf_token %}
           <div class="row">
             <div class="col-md-12">
              <div class="form-group">
                <label for="supplier full name">fulname name</label>
                <input type="text" name= "supplier_full_name" class="form-control">
              </div>
              <div class="form-group">
                <label for="Supplier phone number">phone number</label>
                <input type="number" name= "supplier_phone_number" class="form-control">
              </div>
              <div class="form-group">
                <label for="select2SinglePlaceholder" class="d-block"> Select gender</label>
                <select class="select2-single-placeholder form-control" name="gender" id="select2SinglePlaceholderSupplier" style="width: 100%;padding:10px">
                  <option value="">Select</option>
                  <option value="Male">Male</option>
                  <option value="Female">Female</option>
                </select>
              </div>
              {% if get_all_products %}
              <div class="form-group">
                <label for="select2SinglePlaceholder" class="d-block"> which product?</label>
                <select class="select2-single-placeholder-product form-control" name="product_name" id="select2SinglePlaceholderproduct" style="width: 100%;padding:10px">
                  <option value="">Select</option>
                  {% for product in get_all_products %}
                  <option value="{{product.id}}">{{product}}</option>
                  {% endfor %}
                </select>
              </div>
              {% endif %}
            <button type="submit" class="btn btn-outline-primary ml-1" name="add_supplier" value="add_supplier">add supplier</button>

           </div>
          </form>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Close</button>

    </div>
  </div>
</div>
</div>
</div>

duka/templates/store/suppliersDatatables.html
<div class="tabe_section">
{% include './supplierModal.html' %}
 
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-12 col-lg-12 mb-4">
        <div class="card">
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">My Suppliers</h6>
            <button type="button" class="btn  btn-outline-primary" data-toggle="modal" data-target="#supplierModal"
            id="#supplierModal"><i class="fas fa-plus p-1"></i>Supplier</button>
          </div>
          <div class="table-responsive pl-2">
            <table class="table align-items-center table-flush table-hover" id="dataTableHover">
              <thead class="thead-light">
                <tr>
                 
                  <th>Supplier Name</th>
                  <th>phone no</th>
                  <th>Gender</th>
                  <th>products</th>
                  <th>Since </th>
                  <th>Action</th>
                </tr>
              </thead>
              {% if get_all_suppliers %}
              <tbody>
                {% for suppliers in get_all_suppliers %}
                <tr>
                  <td>{{suppliers.supplier_full_name}} </td>
                  <td>{{suppliers.supplier_phone_number}} </td>
                  <td>{{suppliers.gender}} </td>
                  <td>{{suppliers.product_name}} </td>
                  <td>{{suppliers.updated_at}} </td>
                  <td>
                    <a data-toggle="modal" data-target="#suppliersDetailViewModal{{suppliers.id}}" class="btn btn-sm btn-outline-primary text-primary"><i class="fas fas fa-eye"></i></a>
                    <a  data-toggle="modal" data-target="#updateSuppliersModal{{suppliers.id}}"
                    class="btn btn-sm btn-outline-warning"  ><i class="fas fas fas fa-pen"></i></a>
                    <a  data-toggle="modal" data-target="#deleteSuppliersModal" class="btn btn-sm btn-outline-danger"><i class="fas fas fas far fa-trash-alt"></i></a>
                  </td>
                </tr>
                {% include './deleteSuppliersModal.html' %}
               {% include './suppliersDetailViewModal.html' %}
               {% include './updateSuppliersModal.html' %}
              {% endfor %}
          
              </tbody>
              {% endif %}
            </table>
          </div>
          <div class="card-footer"></div>
        </div>
      </div>
    </div>
  </div>
</div>

duka/templates/store/updateEmployeeModal.html
<div class="modal  fade w3-animate-zoom" id="updateEmployeeModal{{employee.id}}">
  <div class="modal-dialog  modal-dialog-centered">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title"><strong>Update employee info {{forloop.counter}} </strong></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <div class="card mb-4">

          <div class="card-body">
            <form  action="" method="POST">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-6">
                 <div class="form-group">
                   <input type="text"  name="employeeId" value="{{employee.id}}"  style="display:None;">
                   <label for="ProductName">Employee Full name</label>
                   <input type="text" name= "employee_Full_name" value="{{employee.employee_Full_name}}" class="form-control">
                 </div>
                 <div class="form-group">
                   <label for="select2SinglePlaceholder">Select employee gender</label>
                   <select class="select2-single-placeholder form-control mb-3" name="employee_gender"  id="select2SinglePlaceholderEmployeeGender_{{forloop.counter}}" style="width: 100%;">
                     <option  selected value="{{employee.employee_gender}}">{{employee.employee_gender}}</option>
                     <option value="Male">Male</option>
                     <option value="Female">Female</option>
                     </select>
                   
                 </div>
                 <div class="form-group">
                   <label for="exampleFormControlInput1">Email address</label>
                   <input type="email" name = 'employee_email_address'  value ="{{employee.employee_email_address}}" class="form-control" id="exampleFormControlInput1"
                     placeholder="name@example.com">
                 </div>
                 <!-- <div class="form-group">
                   <label for="Supplier" >Start date</label>
                   <input type="date" name="employee_start_date" value="{{employee.employee_start_date}}" class="form-control">
                 </div> -->
                 <div class="form-group">
                  <label for="Supplier" >phone number1</label>
                  <input type="text" name="employee_phone_number1"  value = "{{employee.employee_phone_number1}}" class="form-control">
                </div>
                <div class="form-group">
                  <label for="Supplier" >phone number2</label>
                  <input type="text" name="employee_phone_number2" value = "{{employee.employee_phone_number2}}"  class="form-control">
                </div>            
                </div>
                <div class="col-md-6">
                  
                 <div class="form-group">
                   <label for="Supplier" >Residence area</label>
                   <input type="text" name="employee_residence_area" value = "{{employee.employee_residence_area}}" class="form-control">
                 </div>
                 {% if employee.employee_username %}
                 <div class="form-group">
                  <label for="ProductName">Username</label>
                  <input type="text" name= "username" value="{{employee.employee_username}}" class="form-control">
                </div>
                <div class="form-group">
                  <label for="ProductName">Password</label>
                  <input type="password" name= "password1" value="{{employee.employee_password}}" class="form-control">
                </div>
                <div class="form-group">
                  <label for="ProductName">confirm Password</label>
                  <input type="password" name= "password2" value="{{employee.employee_password}}" class="form-control">
                </div>
                {% else %}
                <div class="form-group">
                  <label for="ProductName">Username</label>
                  <input type="text" name= "username" value="None" class="form-control">
                </div>
                <div class="form-group">
                  <label for="ProductName">Password</label>
                  <input type="password" name= "password1" value="No password" class="form-control">
                </div>
                <div class="form-group">
                  <label for="ProductName">confirm Password</label>
                  <input type="password" name= "password2" value="No password" class="form-control">
                </div>
                {% endif %}    
               </div>
               <button type="submit" class="btn btn-primary ml-3" name="update_employee" value="update_employee">Update employee</button>
              </div>
            </form>
          </div>
        </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>


<script>
  // $(document).ready(function () {


  
    // Select2 Single  with Placeholder
    $('#select2SinglePlaceholderEmployeeGender_{{forloop.counter}}').select2({
      placeholder: "Select",
      allowClear: true
    });      

  // });
  alert('{{forloop.counter}}');

</script>